### PR TITLE
Add support for missing emendatusenigmatica ores/chunks in the mechanical squeezer

### PR DESCRIPTION
**Pull request by TiphaineLAURENT**
Add supports for iron, gold and aluminum

### CODE REVIEW

**Comment by snaiperskaya** [comment]
I think we might be able to do this even easier by using the #forge:ores/X tag

['iron', 'gold', 'aluminum'].forEach(ore => {
		event.custom({
			'type': 'integrateddynamics:mechanical_squeezer',
			'item': `#forge:ores/${ore}`,
			'result': {
				'items': [
					{
						'tag': `forge:dusts/${ore}`,
						'count': 2
					},
					{
						'tag': `forge:dusts/${ore}`,
						'chance': 0.5
					}
				]
			},
			'duration': 40
		})

I'll test with this and see if it works

**Comment by snaiperskaya** [comment]
Also, I might manually merge this because I still want to leave to chunk-to-ore crafting recipe I added (which would also fix things like Astral)

**Comment by TiphaineLAURENT** [comment]
Yes, I forgot to test this one. I did test `'tag': 'emendatusenigmatica:${ore}_ore'` but it does not work

**Comment by snaiperskaya** [comment]
I got this working and updated fixes.js

It'll be in the next update of Snaicraft. For now, you can use the ore conversion recipes I added in 1.3.4

**Pull request closed without merging**
